### ISSUE TITLE
Recurring "Resource of type 'AWS::SageMaker::Domain' with identifier 'ds-studio-domain' did not stabilize."

### ISSUE THREAD

**Issue by Analect** [aws-samples/amazon-sagemaker-studio-secure-data-science-workshop#10]
**Describe the bug**
In Lab 2, when trying to provision a Sagemaker Studio Product ... it keeps failing with `Resource handler returned message: "Resource of type 'AWS::SageMaker::Domain' with identifier 'ds-studio-domain' did not stabilize."`. It's unclear to me how to debug this.

Here is the full error message:
```
Failed to launch provisioned product
Errors from CloudFormation: [{LogicalResourceId : SC-xxx-pp-gbmpqjipskpmg, ResourceType : AWS::CloudFormation::Stack, StatusReason : The following resource(s) failed to create: [SageMakerStudioDomain]. Rollback requested by user.}, {LogicalResourceId : SageMakerStudioDomain, ResourceType : AWS::SageMaker::Domain, StatusReason : Resource handler returned message: "Resource of type 'AWS::SageMaker::Domain' with identifier 'ds-studio-domain' did not stabilize." (RequestToken: 9f7f7782-7dec-8682-afa3-6d996b05982e, HandlerErrorCode: NotStabilized)}, {LogicalResourceId : SageMakerStudioDomain, ResourceType : AWS::SageMaker::Domain, StatusReason : Resource creation Initiated}, {LogicalResourceId : KeyAlias, ResourceType : AWS::KMS::Alias, StatusReason : Resource creation Initiated}, {LogicalResourceId : DataScientistDefaultRoleArn, ResourceType : AWS::SSM::Parameter, StatusReason : Resource creation Initiated}, {LogicalResourceId : SageMakerCustomImageAppConfig, ResourceType : AWS::SageMaker::AppImageConfig, StatusReason : Resource creation Initiated}, {LogicalResourceId : SageMakerCustomImageVersion, ResourceType : AWS::SageMaker::ImageVersion, StatusReason : Resource creation Initiated}, {LogicalResourceId : SageMakerCustomImage, ResourceType : AWS::SageMaker::Image, StatusReason : Resource creation Initiated}, {LogicalResourceId : SagemakerStudioKMS, ResourceType : AWS::KMS::Key, StatusReason : Resource creation Initiated}, {LogicalResourceId : DataScientistDefaultRole, ResourceType : AWS::IAM::Role, StatusReason : Resource creation Initiated}, {LogicalResourceId : SC-xxx-pp-gbmpqjipskpmg, ResourceType : AWS::CloudFormation::Stack, StatusReason : User Initiated}]
```

**To Reproduce**
I have followed steps in Lab1 and Lab2 [here](https://catalog.us-east-1.prod.workshops.aws/workshops/c882cd42-8ec8-4112-9469-9fab33471e85/en-US).

These were the parameters in the launch template

![image](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/assets/4063815/8e76ace1-aff7-4d4a-8f8c-a8f674addfd2)

**Expected behavior**
For the `ds-studio-domain` to have been provisioned without error.

**Screenshots**
This is the point in the CloudFormation events when it fails and reverses course, deleting resources previously created. I retried 3x times, but to no avail.

![image](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/assets/4063815/6b2d5de7-3b5a-4735-b5ba-e00a5a994dc3)

Any suggestions on how I might troubleshoot this more effectively.
 Thanks

**Comment by Analect** [comment]
The error surfaced from the Service Catalog suggests that the stack name is somehow not appropriately meeting a regex contstraint.

![image](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/assets/4063815/24306bba-d8b6-41a1-9953-7a13e54b5737)

It's not clear to me where this constraint is getting applied. It doesn't appear to be in this repo's code.

![image](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/assets/4063815/bf5e8899-f5d2-4ac7-b691-491c546c09bf)

**Comment by sachin-pharande** [comment]
In Lab 2, when trying to provision a Sagemaker Studio Product ... it keeps failing with Resource handler returned message: "Resource of type 'AWS::SageMaker::Domain' with identifier 'ds-studio-domain' did not stabilize."

The error message is as below:

Failed to launch provisioned product
Errors from CloudFormation: [{LogicalResourceId : SC-xxx-pp-gbmpqjipskpmg, ResourceType : AWS::CloudFormation::Stack, StatusReason : The following resource(s) failed to create: [SageMakerStudioDomain]. Rollback requested by user.}, {LogicalResourceId : SageMakerStudioDomain, ResourceType : AWS::S
![Lab-2-SageMaker_Studio_Product Launch error](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/assets/121599759/5848ad32-0b06-4801-b7e6-a7743e81382a)
![Lab-2-SageMaker_Studio_Product Launch error](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/assets/121599759/6d281d9d-cdf4-4741-aa2a-c7bae025f80d)
ageMaker::Domain, StatusReason : Resource handler returned message: "Resource of type 'AWS::SageMaker::Domain' with identifier 'ds-studio-domain' did not stabilize." (RequestToken: 9f7f7782-7dec-8682-afa3-6d996b05982e, HandlerErrorCode: NotStabilized)}, {LogicalResourceId : SageMakerStudioDomain, ResourceType : AWS::SageMaker::Domain, StatusReason : Resource creation Initiated}, {LogicalResourceId : KeyAlias, ResourceType : AWS::KMS::Alias, StatusReason : Resource creation Initiated}, {LogicalResourceId : DataScientistDefaultRoleArn, ResourceType : AWS::SSM::Parameter, StatusReason : Resource creation Initiated}, {LogicalResourceId : SageMakerCustomImageAppConfig, ResourceType : AWS::SageMaker::AppImageConfig, StatusReason : Resource creation Initiated}, {LogicalResourceId : SageMakerCustomImageVersion, ResourceType : AWS::SageMaker::ImageVersion, StatusReason : Resource creation Initiated}, {LogicalResourceId : SageMakerCustomImage, ResourceType : AWS::SageMaker::Image, StatusReason : Resource creation Initiated}, {LogicalResourceId : SagemakerStudioKMS, ResourceType : AWS::KMS::Key, StatusReason : Resource creation Initiated}, {LogicalResourceId : DataScientistDefaultRole, ResourceType : AWS::IAM::Role, StatusReason : Resource creation Initiated}, {LogicalResourceId : SC-xxx-pp-gbmpqjipskpmg, ResourceType : AWS::CloudFormation::Stack, StatusReason : User Initiated}]


A request to provide the guidelines on above aspect...

**Comment by cremich** [comment]
I faced the same issue. @Analect did you find a workaround?

**Comment by cremich** [comment]
@Analect AWS support helped me to fix it. In my case the error was related to a missing permission:

>   User: arn:aws:sts::xxxxx:assumed-role/DSSharedServices-ServiceCatalogLaunchRole-xxxxx/servicecatalog is not authorized to perform: elasticfilesystem:TagResource on the specified resource"

I updated the permissions in the role. After this, the stack was created.

**Comment by sandwi** [comment]
Thanks @cremich for helping the community by sharing the solution to the issue. I have added this role to SCLaunchRole, commit [ad2d034](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/commit/ad2d0341cef2f72b5fb7be495959cfd5d9784ca1).

@Analect can you do a pull of latest and validate that if this also resolves your issue? I will leave this issue open until you or @cremich confirm. Thanks for the help.

**Comment by sandwi** [comment]
commit [ad2d034](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/commit/ad2d0341cef2f72b5fb7be495959cfd5d9784ca1) fixed the issue.
