### ISSUE TITLE
SageMakerVPCDetectiveControl Creation Failed "The runtime parameter of python3.6 is no longer supported..."

### ISSUE THREAD

**Issue by RLashofRegas** [aws-samples/amazon-sagemaker-studio-secure-data-science-workshop#3]
**Describe the bug**
When following the instructions in the associated workshop, the step to create the initial ds_administration stack failed. This is due to the nested "SageMakerDetectiveControl" stack failing because the lambda function referenced is using a deprecated python version.

**To Reproduce**
1. clone repo
2. set appropriate env variables
3. run `./package_cloudformation.sh`
4. run the command that is printed to deploy the CF stack.
5. See error.

**Comment by oodog0126** [comment]
I try to change cloudformation/ds_admin_detective.yaml 
python 3.6 to python 3.8

Then all become normal!

**Comment by sandwi** [comment]
Accepted PR to update python version to 3.7.
