### ISSUE TITLE
Domain level security group should not be used for individual user-profile

### ISSUE THREAD

**Issue by atiur** [aws-samples/amazon-sagemaker-studio-secure-data-science-workshop#8]
#### Reference code
https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/blob/b5505cc857f00fab178f476706dc5610e8714de6/cloudformation/ds_env_studio_user_profile_v1.yaml#L348

#### Current setup
The above code [here](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/blob/b5505cc857f00fab178f476706dc5610e8714de6/cloudformation/ds_env_studio_user_profile_v1.yaml#L348) uses the same, domain level security group for each user-profile in the domain. This security group is created [here](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/blob/b5505cc857f00fab178f476706dc5610e8714de6/cloudformation/ds_shared_sagemaker_network.yaml#L247). This security group later adds an ingress to itself [here](https://github.com/aws-samples/amazon-sagemaker-studio-secure-data-science-workshop/blob/b5505cc857f00fab178f476706dc5610e8714de6/cloudformation/ds_shared_sagemaker_network.yaml#L260-L261).

#### Problem with current setup
In this setup, all app instances in the domain will be able to talk to each other because of this over permissive security group. Anyone who blindly uses this code will end up with their users being able to access each other's apps. This sample code is causing customer confusion. Some customers may remain blind to the issue unless they are checking VPC flow logs or goes through a pentesting process.

#### Recommended fix
1. Remove domain level security group ingress to itself. Keep that security group for common access patterns like apps being able to access VPCE/Privatelink, certain customer subnet, and IGW (if so desired)
2. Use Jinja2 or similar to create per user security-group in the CFN template where each security group allows ingress to itself but one user level security group is not allowed ingress into another

**Comment by sandwi** [comment]
The issue has been resolved. Separate SageMaker domain level security group from user profile level security group. Removed SageMaker domain level security group ingress to itself. It is used for VPC Endpoint.

**Comment by sandwi** [comment]
Separated SageMaker domain level security group from user profile level security group. Removed SageMaker domain level security group ingress to itself. It is only used for VPC Endpoint traffic in SM Exec Policy.
